# In-Class Programming Activity, Day 3
# Qinxi Wang

## Task 1 
```{r}
library("ISLR")
data(College, package = "ISLR")
```

## Task 2
```{r}
Yield = with(College, Enroll/Accept)
College["Yield"] = Yield
```

## Task 3
```{r}
all_indices = 1:length(College[,1])
train_indices = sample(all_indices, 200) 
test_indices = setdiff(all_indices, train_indices) 
Train_data = College[train_indices,]
Test_data = College[test_indices,]
```

## Task 4
```{r}
Yield_mod1 <- lm(Yield[train_indices] ~ Top10perc[train_indices] + Outstate[train_indices] + Expend[train_indices], data=Train_data)
```

## Task 5
```{r}
Y_train = Train_data$Yield
fhat_train = predict(Yield_mod1, newdata = Train_data)
MSE_train = mean(summary(Yield_mod1)$residuals^2)
```

## Task 6
```{r}
Yield_mod2 <- lm(Yield[test_indices] ~ Top10perc[test_indices] + Outstate[test_indices] + Expend[test_indices], data=Test_data)

Y_test = Test_data$Yield
fhat_test = predict(Yield_mod2, newdata = Test_data)
MSE_test = mean(summary(Yield_mod2)$residuals^2)
```

## Test statements

```{r}
scoreActivity::score253(3)
```