# In-Class Programming Activity, Day 6

```{r}
library(mosaicData)
```

### Task 1
```{r}
make_one_bar <- function(point) {
  xLeft <- point$xL
  xRight <- point$xR
  height <- point$count
  res <- data.frame(x = c(xLeft,  xLeft,  xRight, xRight, NA),y = c(0, height,height, 0, NA))
  res
}

one_to_many <- function(hist_data) {
  bars <- NULL
  for (k in 1:nrow(hist_data)) {
    new_bar <- make_one_bar(hist_data[k, ])
    bars <- rbind(bars, new_bar)
  }
  bars
}

myHistogram = function(data, nbins = 10, fill = "tomato"){
  
  evenly_spaced = seq(min(data), max(data), length=nbins+1)
  bins = cut(data, breaks = evenly_spaced)
  bin_counts = table(bins)
  
  xR = evenly_spaced[-1]
  xL = evenly_spaced[-length(evenly_spaced)]
  count = as.numeric(bin_counts)
  hist_basics = data.frame(xR, xL, count)
  My_bars = one_to_many(hist_basics)
  
  plot(My_bars, type="n") 
  lines(My_bars$x, My_bars$y)
  #lines(dnorm(mean(data), sd(data)))
  polygon(My_bars$x, My_bars$y, col = fill)
  xpts = seq(min(data), max(data),length = 100)
  ypts = dnorm(xpts, mean = mean(data), sd = sd(data))
  lines(xpts, ypts*length(data)*diff(evenly_spaced[1:2]), lwd = 3, col = "red")
  return(as.numeric(bin_counts))
}

myHistogram(Galton$height, 11, "blue")
```

```{r}
myHistogram(rnorm(1000), 25)
```


### Task 2
```{r}
v = rnorm(10, mean = 100, sd = 1)
dens = function(x){
  bw = diff(range(x)) / sqrt(length(x))
  xpt = seq(min(x) - 2 * bw, max(x) + 2 *bw, length = 100)
  kernel <- function(eval_pts, where) {
    dnorm(eval_pts, mean = where, sd = bw)
  }
  Dvals <- outer(xpt, x,  FUN = kernel)
  total <- rowSums(Dvals)
  plot(xpt, total, type = "l")
  
  #return(splinefun(xpt, total))

}
```

```{r}
dens(Galton$height)
dens(rnorm(100))
dens(runif(1000))
#f <- dens(runif(1000))
```

#2
x = rnorm(10, mean = mean(v) + 1, sd = 1)

#3
(Dvals = outer(v,x, FUN = kernel))

#4
density = colSums(Dvals)/length(v)

#5
data.frame(x, density)

### Task 3
```{r}
plotdensity = function(v, xlim = NULL){
  return(dens(v))
}
```




## Test statements

```{r}
scoreActivity::score253(6)
```