# In-Class Programming Activity, Day 12

Your work goes here ...
```{r}
n_cases = 100
red_mean = c(1,0)
green_mean = c(0,-1)
blue_mean = c(-1,1)
covar_red = cbind(c(3, -1.7),c(-1.7,1))
covar_blue = cbind(c(2, 1.5),c(1.5,3))

One = cbind(rnorm(n_cases), rnorm(n_cases))
Two = cbind(rnorm(n_cases), rnorm(n_cases))
Three = cbind(rnorm(n_cases), rnorm(n_cases))

  
Red = One %*% chol(covar_red)
Green = Two %*% chol(covar_red)
Blue = Three %*% chol(covar_blue)

Red[,1] = Red[,1] + red_mean[1]
Red[,2] = Red[,2] + red_mean[2]

Green[,1] = Green[,1] + green_mean[1]
Green[,2] = Green[,2] + green_mean[2]

Blue[,1] = Blue[,1] + blue_mean[1]
Blue[,2] = Blue[,2] + blue_mean[2]
```

```{r}

Blue = data.frame(x = Blue[,1], y = Blue[,2], class = "blue", stringsAsFactors = FALSE)
Red = data.frame(x = Red[,1], y = Red[,2], class = "red", stringsAsFactors = FALSE)
Green = data.frame(x = Green[,1], y = Green[,2], class = "green", stringsAsFactors = FALSE)

```


```{r}
Same_sigma = rbind(Red, Green)
Different_sigma = rbind(Red, Blue)
```


```{r}
library(MASS)
mod_LDA_one <- lda(class ~ x + y, data = Same_sigma)
test_LDA_one <- predict(mod_LDA_one, newdata = Same_sigma)

mod_QDA_one <- qda(class ~ x + y, data = Same_sigma)
test_QDA_one <- predict(mod_QDA_one, newdata = Same_sigma)


mod_QDA_two <- qda(class ~ x + y, data = Different_sigma)
test_QDA_two <- predict(mod_QDA_two, newdata = Different_sigma)

mod_LDA_two <- lda(class ~ x + y, data = Different_sigma)
test_LDA_two <- predict(mod_LDA_two, newdata = Different_sigma)

```

```{r}
table(Same_sigma$class, test_LDA_one$class)
table(Different_sigma$class, test_QDA_two$class)
table(Different_sigma$class, test_LDA_two$class)
```

Compare the confusion matrix from LDA on Same sigma to that from QDA based on Same_sig, Which one shows better performance?
###QDA performs better
=======
```
>>>>>>> bf85c5d3a3ca76e82748de682fbfc963c092e748

Compare the confusion matrix from LDA on Same sigma to that from QDA based on Same_sig, Which one shows better performance?

Fit both LDA and QDA models to Sim_two. Which one performs better?
<<<<<<< HEAD
### Still QDA
=======
>>>>>>> bf85c5d3a3ca76e82748de682fbfc963c092e748

## Test statements

```{r}
scoreActivity::score253(12)
```