# In-Class Programming Activity, Day 15


```{r}
library(glmnet)
load("mona.rda")
```

```{r}
X = t(mona) - mean(mona[])
X_rand = matrix(rnorm(191*250), ncol = 191)
A <- chol(cov(X))
X_corr <- X_rand %*% A
```

```{r}
beta = sample(c(rep(0, 175), rep(2, 4), rep(-3, 4), rep(-4,4), rep(5, 4)))
```

```{r}
Y_pure = X %*% beta
Y_real = X %*% beta + rnorm(250, sd = sqrt(var(Y_pure) * 0.1))
```

```{r}
beta_est <- coef(lm(Y_pure ~ X - 1))
plot(beta, beta_est)
best_est_real <- coef(lm(Y_real ~ X - 1))
plot(beta, best_est_real)
```

```{r}
#lm(Y_pure ~ X)
beta_hat_pure = coef(lm(Y_pure ~ X - 1))
plot(beta_hat_pure ~ beta)
beta_hat_real = coef(lm(Y_real ~ X - 1))
plot(beta_hat_real ~ beta)
```

```{r}
lasso_mod <- cv.glmnet(X, Y_real, alpha=1)
beta_lasso <-predict(lasso_mod, type = "coefficients", s = lasso_mod$lambda.min)
```

```{r}
sing_vals = svd(X)$d
r_sqr = cumsum(sing_vals^2) / sum(sing_vals^2)
sing_vals_X_rand = svd(X_rand)$d
sing_vals_X_corr = svd(X_corr)$d
r_sqr_rand = cumsum(sing_vals_X_rand^2) / sum(sing_vals_X_rand^2)
r_sqr_corr = cumsum(sing_vals_X_corr^2) / sum(sing_vals_X_corr^2)

n99 = min(which(r_sqr > 0.99))
n99_rand = min(which(r_sqr_rand > 0.99))
n99_corr = min(which(r_sqr_corr > 0.99))
```

```{r}
library(pls)
pcr.fit <-pcr(Y_real ~ X, scale = TRUE, validation="CV")
```


## Test statements

```{r}
scoreActivity::score253(15)
```