# In-Class Programming Activity, Day 17

```{r}
library(tree)
library(mosaicData)
```


```{r}
Cartoon_data = data.frame(
  x = 1:8,
  y = c(2,5,1,3,8,5,4,6),
  class = c("A", "B", "A", "A", "B", "B", "A", "B")
)

```

```{r}
#Regression tree
pure = tree.control(8, mincut = 0, minsize = 1, mindev = 0)
rtree_pure = tree(y~x, data = Cartoon_data, control = pure)
plot(rtree_pure)
text(rtree_pure)
```

```{r}
#Classification tree
ctree_pure = tree(class ~ x, data = Cartoon_data, control = pure)
plot(ctree_pure)
text(ctree_pure)
```

```{r}
predict(rtree_pure)
predict(ctree_pure)
predict(rtree_pure, newdata = data.frame(x=3))
predict(ctree_pure, newdata = data.frame(x =7))
```

```{r}
rtree_5 = prune.tree(rtree_pure, best = 5)
ctree_2 = prune.misclass(ctree_pure, best = 2)
deviance(rtree_5)
deviance(ctree_2)
nterminal = c(2:8)
tree_deviance = function(n) {
  ntree <- prune.tree(rtree_pure, best = n)
  deviance(ntree)
}
sapply(2:8, FUN = tree_deviance)  
```

```{r}
pure_for_cps = tree.control(nrow(CPS85), mincut = 0, minsize = 1, mindev = 0)
Sector_classifier = tree(sector ~ wage + sex + educ + exper, data = CPS85, control = pure_for_cps)
terminal20 = prune.tree(Sector_classifier, 20)
plot(terminal20)
text(terminal20)
```


## Test statements

```{r}
#scoreActivity::score253(17)
```